version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8081:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    form-node:
        build: .
        # ports:
        #     - '8081:8081'
        volumes:
            - ./:/app
            - /app/node_modules
